name: Build DS918+_7.0.1-42218

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     - name: Chmod
        run: chmod 0755 ./build-ds918-7.0.1.sh
      - name: Build DS918+ 7.0.1
        run: ./build-ds918-7.0.1.sh

     - uses: actions/upload-artifact@v3
        with:
          name: redpill-DS918+_7.0.1-42218
          path: ./img

